# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to VPS - DataStructViz

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build app
        run: dotnet build --configuration Release

      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      - name: Upload published app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 188.214.88.98 >> ~/.ssh/known_hosts

      - name: Deploy app to VPS via rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ root@188.214.88.98:/var/www/datastructviz

      - name: Restart systemd service on VPS
        run: |
          ssh -i ~/.ssh/id_rsa root@188.214.88.98 "sudo systemctl restart datastructviz.service"

          