# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Blazor App Docker to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t abalan95/blazorapp:latest2 .

      - name: Push Docker image to Docker Hub
        run: |
          docker push abalan95/blazorapp:latest2

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 188.214.88.98 >> ~/.ssh/known_hosts

      - name: Pull and restart Docker container on VPS
        run: |
          ssh -i ~/.ssh/id_rsa root@188.214.88.98 << 'EOF'
            docker pull abalan95/blazorapp:latest2
            docker stop elegant_nobel || true
            docker rm elegant_nobel || true
            docker run -d \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
              -e DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}" \
              -p 80:80 \
              --name elegant_nobel \
              abalan95/blazorapp:latest2
          EOF



          